import { describe, expect, it } from "vitest";
import rehypeCustomToc, { type RehypeCustomTocOptions } from "./index";
import remarkComment from "remark-comment";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";
import { unified } from "unified";

/**
 * A comment node generated by the `remark-comment` plugin.
 */
interface Comment extends Node {
    type: "comment";
    value: "";
    commentValue: string;
}

const createProcessor = (options?: RehypeCustomTocOptions) => {
    const processor = unified()
        .use(remarkParse)
        .use(remarkComment, {
            ast: true
        })
        .use(remarkRehype, {
            handlers: {
                /**
                 * Convert a mdast comment node to a hast comment node.
                 * @param _ State
                 * @param node mdast comment node
                 * @returns hast comment node
                 */
                comment: (_, node: Comment) => ({
                    type: "comment",
                    value: node.commentValue
                })
            }
        })
        .use(rehypeCustomToc, options)
        .use(rehypeStringify);

    return processor;
};

const normalizeHtml = (html: string) => html.replace(/>\s+</g, "><").trim();

const markdown = `
# Title

This is a sample markdown paragraph.

<!-- toc -->

## Section 1

### Subsection 1.1

#### Subsection 1.1.1
`.trim();

describe("rehype-custom-toc", () => {
    it("matches the README example output", async () => {
        const processor = createProcessor();
        const result = await processor.process(markdown);

        const expected = `
<h1 id="title">Title</h1>
<p>This is a sample markdown paragraph.</p>
<aside class="toc">
    <h2>Contents</h2>
    <nav>
        <ul>
            <li><a href="#title">Title</a></li>
            <ul>
                <li><a href="#section-1">Section 1</a></li>
                <ul>
                    <li><a href="#subsection-11">Subsection 1.1</a></li>
                </ul>
            </ul>
        </ul>
    </nav>
</aside>
<h2 id="section-1">Section 1</h2>
<h3 id="subsection-11">Subsection 1.1</h3>
<h4 id="subsection-111">Subsection 1.1.1</h4>`.trim();

        expect(normalizeHtml(result.toString())).toBe(normalizeHtml(expected));
    });

    it("uses a custom template when provided", async () => {
        const processor = createProcessor({
            template: (html) => `<div class="toc-wrapper">${html}</div>`
        });
        const result = await processor.process(markdown);

        const expected = `
<h1 id="title">Title</h1>
<p>This is a sample markdown paragraph.</p>
<div class="toc-wrapper">
    <ul>
        <li><a href="#title">Title</a></li>
        <ul>
            <li><a href="#section-1">Section 1</a></li>
            <ul>
                <li><a href="#subsection-11">Subsection 1.1</a></li>
            </ul>
        </ul>
    </ul>
</div>
<h2 id="section-1">Section 1</h2>
<h3 id="subsection-11">Subsection 1.1</h3>
<h4 id="subsection-111">Subsection 1.1.1</h4>`.trim();

        expect(normalizeHtml(result.toString())).toBe(normalizeHtml(expected));
    });

    it("respects maxDepth of 2", async () => {
        const processor = createProcessor({
            maxDepth: 2
        });
        const result = await processor.process(markdown);

        const expected = `
<h1 id="title">Title</h1>
<p>This is a sample markdown paragraph.</p>
<aside class="toc">
    <h2>Contents</h2>
    <nav>
        <ul>
            <li><a href="#title">Title</a></li>
            <ul>
                <li><a href="#section-1">Section 1</a></li>
            </ul>
        </ul>
    </nav>
</aside>
<h2 id="section-1">Section 1</h2>
<h3 id="subsection-11">Subsection 1.1</h3>
<h4 id="subsection-111">Subsection 1.1.1</h4>`.trim();

        expect(normalizeHtml(result.toString())).toBe(normalizeHtml(expected));
    });

    it("respects maxDepth of 4", async () => {
        const processor = createProcessor({
            maxDepth: 4
        });
        const result = await processor.process(markdown);

        const expected = `
<h1 id="title">Title</h1>
<p>This is a sample markdown paragraph.</p>
<aside class="toc">
    <h2>Contents</h2>
    <nav>
        <ul>
            <li><a href="#title">Title</a></li>
            <ul>
                <li><a href="#section-1">Section 1</a></li>
                <ul>
                    <li><a href="#subsection-11">Subsection 1.1</a></li>
                    <ul>
                        <li><a href="#subsection-111">Subsection 1.1.1</a></li>
                    </ul>
                </ul>
            </ul>
        </ul>
    </nav>
</aside>
<h2 id="section-1">Section 1</h2>
<h3 id="subsection-11">Subsection 1.1</h3>
<h4 id="subsection-111">Subsection 1.1.1</h4>`.trim();

        expect(normalizeHtml(result.toString())).toBe(normalizeHtml(expected));
    });

    it("uses ordered lists when ordered is true", async () => {
        const processor = createProcessor({
            ordered: true
        });
        const result = await processor.process(markdown);

        const expected = `
<h1 id="title">Title</h1>
<p>This is a sample markdown paragraph.</p>
<aside class="toc">
    <h2>Contents</h2>
    <nav>
        <ol>
            <li><a href="#title">Title</a></li>
            <ol>
                <li><a href="#section-1">Section 1</a></li>
                <ol>
                    <li><a href="#subsection-11">Subsection 1.1</a></li>
                </ol>
            </ol>
        </ol>
    </nav>
</aside>
<h2 id="section-1">Section 1</h2>
<h3 id="subsection-11">Subsection 1.1</h3>
<h4 id="subsection-111">Subsection 1.1.1</h4>`.trim();

        expect(normalizeHtml(result.toString())).toBe(normalizeHtml(expected));
    });
});
